class AppConstants {
  final String fontMontserrat = 'montserrat';
  final String fontManrope = 'manrope';
  final String isFirstTime = 'isFirstTime';
  final String lat = 'lat';
  final String lng = 'lng';
  final String isLogin = 'isLogin';
  final String jwt = 'jwt';
  final String search = 'Search';
  final String home = 'Home';
  final String aboutUs = 'About us';
  final String contactUs = 'Contact us';
  final String termsAndCondition = 'Term of service';
  final String privacyPolicy = 'Privacy Policy';
  final String empty = '';
  final String continueText = 'Continue';
  final String verify = 'Verify';
  final String register = 'Register';
  final String registration = 'Registration';
  final String profile = 'Profile';
  final String update = 'Update';
  final String getStarted = 'Get started';
  final String onBoardingTitle1 = 'purchase';
  final String onBoardingTitle2 = 'QR Code';
  final String onBoardingTitle3 = 'Discount';
  final String onBoardingSubTitle1 =
      'Pickup the groceries and wearable items from your nearby store and get the best discounts';
  final String onBoardingSubTitle2 =
      'Show your QR to the salesman and collect points for get discounts from the same store';
  final String onBoardingSubTitle3 =
      'Scan your QR code the fast way to Radeem your available points';
  final String discountIsYourRight = 'Discount is your right !';
  final String continueWithYourPhoneNumber = 'Continue with your phone number';
  final String countryCode = '+92';
  final String termAndConditionsText = "By using this application ,you agree to the ";
  final String termOfService = "Term of Service";
  final String termOfUse = "TERMS OF USE";
  final String termOfUseDescription = "These Terms of Use (“Terms”) govern your use of the websites and mobile applications provided by foodpanda (or referred to as “us”) (collectively the “Platforms”). Please read these Terms carefully. By accessing and using the Platforms, you agree that you have read, understood and accepted the Terms including any additional terms and conditions and any policies referenced herein, available on the Platforms or available by hyperlink. If you do not agree or fall within the Terms, please do not use the Platforms.\n\nThe Platforms may be used by (i) natural persons who have reached 18 years of age and (ii) corporate legal entities, e.g companies. Where applicable, these Terms shall be subject to country-specific provisions as set out herein.\n\nUsers below the age of 18 must obtain consent from parent(s) or legal guardian(s), who by accepting these Terms shall agree to take responsibility for your actions and any charges associated with your use of the Platforms and/or purchase of Goods. If you do not have consent from your parent(s) or legal guardian(s), you must stop using/accessing the Platforms immediately. ";
  final String privacyPolicyDescription = "This website uses Google Analytics, a web analytics service provided by Google, Inc. ('Google'). Google Analytics uses 'cookies', which are text files saved on your computer, to help the website analyze how you use the site. The information generated by the cookie about your use of the website will be transmitted to and stored by Google on servers in the United States. If this website anonymizes IP addresses, your IP address will be truncated by Google within a EU member state or other EEA state before being transmitted to the US. Only in exceptional situations will your full IP address be transmitted to Google servers in the United States and truncated there. Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing other services relating to website activity and internet usage. Google will not associate your IP address with any other data held by Google. You may refuse the use of cookies by selecting the appropriate settings on your browser, however please note that if you do this you may not be able to use the full functionality of this website. By using this website, you consent to the processing of data about you by Google in the manner and for the purposes set out above. You can also prevent Google from collecting information (including your IP address) via cookies and processing this information by downloading this browser plugin and installing it:";
}
