name: core
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  cloud_firestore: ^3.1.5
  firebase_remote_config: ^1.0.3
  firebase_messaging: ^11.2.4
  firebase_analytics: ^9.0.4

  # Social
  google_sign_in: ^5.1.0
  flutter_login_facebook: ^1.2.0
  flutter_facebook_auth: ^3.5.7

  #state Management
  get: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
